version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dev.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development